# Generated by Django 5.1 on 2024-11-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_venue', models.CharField(max_length=100)),
                ('cost_of_dish', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks_name', models.CharField(max_length=100)),
                ('drinks_venue', models.CharField(max_length=100)),
                ('drinks_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment_name', models.CharField(max_length=100)),
                ('entertainment_venue', models.CharField(max_length=100)),
                ('entertainment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography_name', models.CharField(max_length=100)),
                ('photography_venue', models.CharField(max_length=100)),
                ('photography_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='venue/')),
                ('video', models.FileField(blank=True, null=True, upload_to='venue/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish1', to='app.dish')),
                ('dish2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish2', to='app.dish')),
                ('dish3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish3', to='app.dish')),
                ('drinks1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks1', to='app.drinks')),
                ('drinks2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks2', to='app.drinks')),
                ('drinks3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks3', to='app.drinks')),
                ('drinks4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks4', to='app.drinks')),
                ('entertainment1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment1', to='app.entertainment')),
                ('entertainment2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment2', to='app.entertainment')),
                ('entertainment3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment3', to='app.entertainment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('photography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photography')),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('number_of_guests', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('booking_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking_venue')),
                ('dish1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish11', to='app.dish')),
                ('dish2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish21', to='app.dish')),
                ('dish3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish31', to='app.dish')),
                ('drinks1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks11', to='app.drinks')),
                ('drinks2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks21', to='app.drinks')),
                ('drinks3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks31', to='app.drinks')),
                ('drinks4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks41', to='app.drinks')),
                ('entertainment1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment11', to='app.entertainment')),
                ('entertainment2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment21', to='app.entertainment')),
                ('entertainment3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment31', to='app.entertainment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('photography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photography')),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
        ),
    ]
