# Generated by Django 5.0.6 on 2024-10-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment_name', models.CharField(max_length=100)),
                ('entertainment_venue', models.CharField(max_length=100)),
                ('entertainment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
