# Generated by Django 5.1 on 2024-11-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_event',
            name='booking_venue',
        ),
        migrations.AlterField(
            model_name='book_event',
            name='venue_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booking_venue'),
        ),
    ]
