# Generated by Django 5.1 on 2024-11-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_event_booking_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_event',
            name='cost_per_day',
        ),
        migrations.RemoveField(
            model_name='book_event',
            name='event',
        ),
    ]
