# Generated by Django 5.0.6 on 2024-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entertainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography_name', models.CharField(max_length=100)),
                ('photography_venue', models.CharField(max_length=100)),
                ('photography_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
