# Generated by Django 5.0.6 on 2024-10-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks_name', models.CharField(max_length=100)),
                ('drinks_venue', models.CharField(max_length=100)),
                ('drinks_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
