# Generated by Django 5.1 on 2024-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_event_cost_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_event',
            name='customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
