# Generated by Django 5.1 on 2024-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_event_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_event',
            name='customer_contact',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
