# Generated by Django 5.1 on 2024-11-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_event',
        ),
    ]
