# Generated by Django 5.1 on 2024-11-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_venue_facilities_remove_venue_venue_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='cost_per_day',
        ),
    ]
