# Generated by Django 5.1 on 2024-11-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_event_customer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful')], default='pending', max_length=10),
        ),
    ]
