# Generated by Django 5.1 on 2024-11-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_venue_cost_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish1', to='app.dish')),
                ('dish2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish2', to='app.dish')),
                ('dish3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish3', to='app.dish')),
                ('drinks1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks1', to='app.drinks')),
                ('drinks2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks2', to='app.drinks')),
                ('drinks3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks3', to='app.drinks')),
                ('drinks4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks4', to='app.drinks')),
                ('entertainment1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment1', to='app.entertainment')),
                ('entertainment2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment2', to='app.entertainment')),
                ('entertainment3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment3', to='app.entertainment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('photography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.photography')),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
        ),
    ]
