# Generated by Django 5.1 on 2024-11-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_venue',
            name='dish1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish1', to='app.dish'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='dish2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish2', to='app.dish'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='dish3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_dish3', to='app.dish'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='drinks1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks1', to='app.drinks'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='drinks2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks2', to='app.drinks'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='drinks3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks3', to='app.drinks'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='drinks4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_drinks4', to='app.drinks'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='entertainment1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment1', to='app.entertainment'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='entertainment2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment2', to='app.entertainment'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='entertainment3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_entertainment3', to='app.entertainment'),
        ),
        migrations.AlterField(
            model_name='booking_venue',
            name='photography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photography'),
        ),
    ]
