# Generated by Django 5.1 on 2024-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_creditcard_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='amount',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
    ]
